def GITHUB_REPO = "https://github.com/Kritika1300/Email-service-.git"
def BRANCH = "main"

pipeline {
    agent any
    stages {
        stage("Code Checkout") {
            steps {
                script {
                    checkout_obj =checkout([
                            $class: 'GitSCM',
                            branches: [[name: "${BRANCH}"]],
                            doGenerateSubmoduleConfigurations: false,
                            extensions: [[$class: 'WipeWorkspace']],
                            submoduleCfg: [],
                            userRemoteConfigs: [[url: "${GITHUB_REPO}"]]
                    ])
                }
            }
        }
        stage("Build Docker Image"){
            steps {
                script {
                    sh ''' cd emailservice && \
                     docker build -f Dockerfile -t gomail.azurecr.io/gomail:latest .
                     '''
                }
            }
        }
        stage("Push Image to ACR") {
            steps {
                script {
                    sh '''az login --service-principal --username <uname> --password <password> --tenant <tenant> && \
                          az acr login --name gomail.azurecr.io && \
                         docker push gomail.azurecr.io/gomail:latest'''
                }
            }
        }
        stage("Deploy Image to Container Apps") {
            steps {
                script {
                    sh 'az containerapp update -n gomail -g gomail --image gomail.azurecr.io/gomail:latest'
                }
            }
        }
    }
}
